### PR TITLE
don't unpack boolean metadata

### PR DESCRIPTION
**Pull request by kbro237**
Here's my simple proposal for #2 

Still new to lua and I'm not 100% certain of how panda and pandoc lua filters work, but this solves the problem on my end.

### CODE REVIEW

**Comment by CDSoft** [comment]
Hello.
Thank you for your patch.
I tried to add some tests and booleans can not simply be stored as booleans (`{{link-citations}}` will crash Pandoc).
I will propose a slightly different solution where non table values are converted to strings.

**Comment by kbro237** [comment]
I wonder why it didn't crash in my tests. Regardless, thank you for finding a better solution!

**Comment by CDSoft** [comment]
Did you try to use the value of `link-citations` in the document with `{{link-citations}}`?
Which version of Pandoc are you using? (mine is pandoc 2.9.2.1)

**Comment by kbro237** [comment]
Oh yes, you're right, I never used the variable in the body. Thanks!

**Pull request closed without merging**
